export const data=[
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    },
    {
        id:1,
        title:'mario',
        price:'$55',
        category:'switch',
        linkImg:'https://i.ytimg.com/vi/1cbxx_RwAUw/maxresdefault.jpg'
    }
]